### ISSUE TITLE
how to use hypnos

### ISSUE THREAD

**Issue by scottpez** [caerusassociates/hypnos#7]
Hi,

Would you mind giving an example of how to use hypnos with petrarch? I'm a little confused. It says that hypnos is a wrapper around petrarch. Does that mean in one request I can call ``/hyonos/extract`` with my data, and have it run through petrarch as if it was running the ``petrarch batch`` command? I ran hypnos with data like this 

``
import json
import requests

headers = {'Content-Type': 'application/json'}
data = {'text': "At least 37 people are dead after Islamist radical group Boko Haram assaulted a town in northeastern Nigeria.", 'id': 'abc123', 'date': '20010101'}
data = json.dumps(data)
r = requests.get('http://localhost:5002/hypnos/extract', data=data, headers=headers)
print r.json()
``

It outputted this which sort of looks like what petrarch wants as an input.

``
{u'abc123': {u'sents': {u'0': {u'content': u'At least 37 people are dead after Islamist radical group Boko Haram assaulted a town in northeastern Nigeria .', u'parsed': u'(ROOT (S (NP (QP (IN AT ) (JJS LEAST ) (CD 37 ) ) (NNS PEOPLE ) ) (VP (VBP ARE ) (ADJP (JJ DEAD ) ) (SBAR (IN AFTER ) (S (NP (JJ ISLAMIST ) (JJ RADICAL ) (NN GROUP ) (NNP BOKO ) (NNP HARAM ) ) (VP (VBD ASSAULTED ) (NP (NP (DT A ) (NN TOWN ) ) (PP (IN IN ) (NP (JJ NORTHEASTERN ) (NNP NIGERIA ) ) ) ) ) ) ) ) (. . ) ) )', u'issues': [[u'ID_EXTREMISM', 1], [u'NAMED_TERROR_GROUP', 1]], u'events': [[u'NGAREBMUS', u'NGA', u'190']]}}, u'meta': {u'date': u'20010101'}}}
``

It seems to be a mix of incorrect JSON and the XML petrarch is expecting. When I run this data through ``petrarch batch`` it complains about the format of the input data.

Therefore, am I able to send hypnos data and have it both extract the text and then run it through petrarch? Or am I supposed to run the text through hypnos and then run the output through ``petrarch batch``? If the latter, is there something wrong with the hypnos code that produces a mix of JSON and XML?

Thank you so much for your guidance.

Also, I had opened this petrarch ticket as a reference.

https://github.com/openeventdata/petrarch/issues/94

Scott

**Comment by johnb30** [comment]
If you look at the `events` key in the output JSON you'll see the coded events. Within that field, `events[0][0]` will be the source actor, `events[0][1]` will be the target, and `events[0][2]` will be the CAMEO code. You can also access the coded issues under the `issues` key.

**Comment by scottpez** [comment]
Thank you John. This seems to be what I want and now I have a better understanding of how hypnos and petrarch work.

**Comment by hannesroos** [comment]
Dear all,
I am also a little confused how to use hypnos. Hypnos is installed and getting it to run with docker compose up -d works, but how to run the data through it? As in where should I put the following code for testing:
"headers = {'Content-Type': 'application/json'}
data = {'text': "At least 37 people are dead after Islamist radical group Boko Haram assaulted a town in northeastern Nigeria.", 'id': 'abc123', 'date': '20010101'}
data = json.dumps(data)
r = requests.get('http://localhost:5002/hypnos/extract', data=data, headers=headers)
print r.json()"
Running it through terminal doesn't seem to work.

Thanks in advance,

Hannes

**Comment by scottpez** [comment]
Hannes, I put the example code in a bash shell script and it worked.

**Comment by sdspieg** [comment]
Following up (I'm a colleague of Hannes') - we were able to make this work by doing the following on a 'clean' ubuntu 14.04 system
1. Install python:
sudo apt-get install python-pip
2. install git
sudo apt-get update
sudo apt-get install git 
3. install docker
git clone https://gist.github.com/f1af16bd7e970389bad3.git
cd f1af16bd7e970389bad3
chmod +x install.sh
./install.shls
4. install petrarch
sudo pip install git+https://github.com/openeventdata/petrarch.git
5. install hypnos
sudo git clone https://github.com/caerusassociates/hypnos.git
6. go into the directory where hypnos is now installed
cd hypnos
7. start hypnos (in the background)
sudo docker-compose up -d
7. start python
python
8. wait for the Python REPL (>>>)
9. enter the code (make sure all the lines 'flow' (no carriage returns or anything) and replace the text with whatever it is you want to code)
import requests
import json
headers = {'Content-Type': 'application/json'}
data = {'text': "At least 37 people are dead after Islamist radical group Boko Haram assaulted a town in northeastern Nigeria.", 'id': 'abc123', 'date': '20010101'}
data = json.dumps(data)
r = requests.get('http://localhost:5002/hypnos/extract', data=data, headers=headers)
r.json()

This will generate, sentence by sentence, an annotated version in which you will see the NLP codes as well as the CAMEO codes.

**Comment by chilland** [comment]
There is no need to install petrarch yourself (step 4). It is included in the Docker container. The example request in the readme is written in python. So yes, you need to start python and run it from there, but you can make the request using whatever you want, including cURL from the command line.

**Comment by sdspieg** [comment]
Ok. Thanks. I just wanted to document something that works - for other noobs like us.  I do have some more questions though. We are now running some texts through this, and want to assess the accuracy of the coding. So let me give one example: 
'The Russian Defense Ministry acknowledged that both men had served in the Russian Army but denied that they were on active duty at the time of their capture’. u'parsed': u'(ROOT (S (NP (DT THE ) (NNP RUSSIAN ) (NNP DEFENSE ) (NNP MINISTRY) ) (VP (VP (VBD ACKNOWLEDGED ) (SBAR (IN THAT ) (S (NP (DT BOTH ) (NNS MEN ) ) (VP (VBD HAD ) (VP (VBN SERVED ) (PP (IN IN ) (NP (DT THE ) (JJ RUSSIAN ) (NNP ARMY ) ) ) ) ) ) ) ) (CC BUT ) (VP (VBD DENIED ) (SBAR (IN THAT ) (S (NP (PRP THEY ) ) (VP (VBD WERE ) (PP (IN ON ) (NP (JJ ACTIVE ) (NN DUTY ) ) ) (PP (IN AT ) (NP (NP (DT THE ) (NN TIME ) ) (PP (IN OF ) (NP (PRP$ THEIR ) (NN CAPTURE ) ) ) ) ) ) ) ) ) ) (. . ) ) )', u'issues': [], u'events': [[u'RUSGOV', u'RUSMIL', u'015']]}, u'21'

Can somebody please parse this for us? RUSGOV as SourceActor seems accurate, but which nlp PoS/dependency did it use to get that?. Code 015 (Acknowledge or claim responsibility) also seems right. But where in the documentation can we find all synonyms etc. that are coded as 015 - just to double-check the case where it seems less obvious? How did it get RUSMIL as TargetActor (also purely nlp-wise)? And what does ‘u/21’ mean?  

Any help would be greatly appreciated - certainly for us, but presumably also for others who are trying to dig into this. 

[And incidentally: if somebody who is following this would be willing and able to help us set up a fully functioning phoenix pipeline on our ubuntu system, please get in touch with me by pm. Thanks!]

**Comment by johnb30** [comment]
@sdspieg 

1) This one is pretty straightforward. PETR looks at the upper end of the sentence and tries to identify the subject, which is, of course, a noun phrase. In this case it finds the noun phrase "Russian Defense Ministry," which gets coded as a `RUSGOV` actor.
2) Verb patterns can be found at https://github.com/openeventdata/Dictionaries/blob/master/CAMEO.verbpatterns.txt. If you search for `015` in there you should see the verb patterns that get coded that way.
3) PETR tries to find the object of the phrase "acknowledged", which in this case it seems to have found "Russian Army." That's what led to the `RUSMIL` code.
4) Not sure where that's coming from. It seems to be outside the return values that `hypnos` provides.

When we release PETR 2 we'll also be releasing some more comprehensive documentation about how the software chooses the noun and verb phrases to code.
